"""empty message

Revision ID: 1e7879ea02a6
Revises: fbf932e829aa
Create Date: 2024-10-12 17:13:43.832407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7879ea02a6'
down_revision = 'fbf932e829aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_assignments')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_constraint('fk_assignments_teacher_id_teachers', type_='foreignkey')
        batch_op.drop_column('teacher_id')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_assignments_teacher_id_teachers', 'teachers', ['teacher_id'], ['id'])
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    op.create_table('_alembic_tmp_assignments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('points_possible', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_assignments_course_id_courses'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
