"""empty message

Revision ID: 210556e90ecc
Revises: 720ffac7c0cc
Create Date: 2024-10-12 12:18:36.493251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210556e90ecc'
down_revision = '720ffac7c0cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    # ### end Alembic commands ###
