"""empty message

Revision ID: 269f14938e55
Revises: 1e7879ea02a6
Create Date: 2024-10-12 18:30:17.317243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269f14938e55'
down_revision = '1e7879ea02a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
