"""empty message

Revision ID: 720ffac7c0cc
Revises: 29b24e2bca87
Create Date: 2024-10-12 12:18:20.280320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720ffac7c0cc'
down_revision = '29b24e2bca87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
