"""empty message

Revision ID: 89b239a8ad00
Revises: 355050a8158c
Create Date: 2024-10-28 12:57:52.143366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b239a8ad00'
down_revision = '355050a8158c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_email', ['email'])

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_email',  ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint('unique_email', 'teachers', type_='unique')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('unique_email', 'students', type_='unique')

    # ### end Alembic commands ###
