"""empty message

Revision ID: d016c0bf89dd
Revises: 269f14938e55
Create Date: 2024-10-12 18:33:28.839104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd016c0bf89dd'
down_revision = '269f14938e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_assignments', schema=None) as batch_op:
        batch_op.drop_column('completed')
        batch_op.drop_column('id')
        batch_op.drop_column('points_earned')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_earned', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
